### PR TITLE
IDEA: All-in-one Python interactive plotting library for genomics

### PR DESCRIPTION
**Pull request by clintval**

### CODE REVIEW

**Review by apfejes — APPROVED** [review]

**Comment by mmoss609** [comment]
Tra t ttt3ttry44 tug y 4444th 4h444th y3h3 and a 54t4rk6 hhr4hhy hiring i3t

**Comment by mmoss609** [comment]
H

**Comment by mmoss609** [comment]
Yr74y hy t rthern 4thh6h64h4thh6trihh6 hh 44a good 4hh I and hy65t47hh4

**Comment by clintval** [comment]
This thread is crazy

**Comment by apfejes** [comment]
I think moss sat on his computer.

**Comment by mmoss609** [comment]
I have no idea how any of this happened. I haven't even been on my computer since yesterday. Sorry for the annoyance though, that's a crazy thing

**Comment by clintval** [comment]
Any chance of a re-open and merge or no?

**Comment by apfejes** [comment]
Sorry - thought it was already merged.

**Pull request merged**
